package com.wonwire.wonwire.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.math.BigDecimal;

/**
 * Request DTO for initiating a transfer between two users.
 * The idempotency key must be generated by the client per transfer attempt to prevent duplicate transactions.
 */
@Data
public class TransferRequestDTO {

    @NotBlank(message = "Recipient email is required")
    private String toEmail;

    @NotNull(message = "Amount is required")
    @DecimalMin(value = "1", message = "Amount must be greater than 1")
    private BigDecimal amount;

    private String description;

    @NotBlank(message = "Idempotency key is required")
    private String idempotencyKey;
}